### PR TITLE
Created lesson for kanban and added GitHub documentation for GitHub P…

### PR DESCRIPTION
**Pull request by ahuynh3a**
@heratyian

### CODE REVIEW

**Comment by ahuynh3a** [comment]
#1

**Review by heratyian — COMMENTED** [review]
This looks great @ahuynh3a! Want to add a couple screenshots and maybe a few quiz questions?

https://github.com/appdev-lessons/how-to-write-a-lesson

**Comment by ahuynh3a** [comment]
Oh that's a good idea! I will work on it! Thank you!

**Review by heratyian — APPROVED** [review]
👍

**Pull request merged**
